### ISSUE TITLE
Ruby version should be based on users ruby

### ISSUE THREAD

**Issue by hovancik** [yurikoval/middleman-gh-pages-action#4]
My Action  fails with `Your Ruby version is 3.2.2, but your Gemfile specified 3.1.3`. 

```
name: Middleman

on:
  push:
    branches: [develop]

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build & Deploy to GitHub Pages
        with:
          REMOTE_BRANCH: trunk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: yurikoval/middleman-gh-pages-action@master
```
